# Supplies a set of blogs to follow
# Useful to provide this data for all accounts (i.e. imported data),
# since a un-authenticated API call doesn't reveal this information

- Name: staff
  Title: Tumblr Staff
  URL: http://staff.tumblr.com/
  PortraitURL-16: "http://30.media.tumblr.com/avatar_013241641371_16.png"
  PortraitURL-24: "http://30.media.tumblr.com/avatar_013241641371_24.png"
  PortraitURL-30: "http://30.media.tumblr.com/avatar_013241641371_30.png"
  PortraitURL-40: "http://30.media.tumblr.com/avatar_013241641371_40.png"
  PortraitURL-48: "http://30.media.tumblr.com/avatar_013241641371_48.png"
  PortraitURL-64: "http://30.media.tumblr.com/avatar_013241641371_64.png"
  PortraitURL-96:  "http://30.media.tumblr.com/avatar_013241641371_96.png"
  PortraitURL-128: "http://30.media.tumblr.com/avatar_013241641371_128.png"              
- Name: jacob
  Title: Jacob Bijani
  URL: http://jacobbijani.com
  PortraitURL-16: "http://30.media.tumblr.com/avatar_5b13c55f0688_16.png"
  PortraitURL-24: "http://30.media.tumblr.com/avatar_5b13c55f0688_24.png"
  PortraitURL-30: "http://30.media.tumblr.com/avatar_5b13c55f0688_30.png"
  PortraitURL-40: "http://30.media.tumblr.com/avatar_5b13c55f0688_40.png"
  PortraitURL-48: "http://30.media.tumblr.com/avatar_5b13c55f0688_48.png"
  PortraitURL-64: "http://30.media.tumblr.com/avatar_5b13c55f0688_64.png"
  PortraitURL-96: "http://30.media.tumblr.com/avatar_5b13c55f0688_96.png"
  PortraitURL-128: "http://30.media.tumblr.com/avatar_5b13c55f0688_128.png"
- Name: petervidani
  Title: Peter Vidani
  URL: http://blog.petervidani.com/
  PortraitURL-16: "http://25.media.tumblr.com/avatar_51777f3c873f_16.png"
  PortraitURL-24: "http://25.media.tumblr.com/avatar_51777f3c873f_24.png"
  PortraitURL-30: "http://25.media.tumblr.com/avatar_51777f3c873f_30.png"
  PortraitURL-40: "http://25.media.tumblr.com/avatar_51777f3c873f_40.png"
  PortraitURL-48: "http://25.media.tumblr.com/avatar_51777f3c873f_48.png"
  PortraitURL-64: "http://25.media.tumblr.com/avatar_51777f3c873f_64.png"
  PortraitURL-96: "http://25.media.tumblr.com/avatar_51777f3c873f_96.png"
  PortraitURL-128: "http://25.media.tumblr.com/avatar_51777f3c873f_128.png"
- Name: marco
  Title: Marco.org
  URL: http://www.marco.org/
  PortraitURL-16: "http://26.media.tumblr.com/avatar_e32e887541c2_16.png"
  PortraitURL-24: "http://26.media.tumblr.com/avatar_e32e887541c2_24.png" 
  PortraitURL-30: "http://26.media.tumblr.com/avatar_e32e887541c2_30.png"
  PortraitURL-40: "http://26.media.tumblr.com/avatar_e32e887541c2_40.png"
  PortraitURL-48: "http://26.media.tumblr.com/avatar_e32e887541c2_48.png"
  PortraitURL-64: "http://26.media.tumblr.com/avatar_e32e887541c2_64.png"
  PortraitURL-96: "http://26.media.tumblr.com/avatar_e32e887541c2_96.png"
  PortraitURL-128: "http://26.media.tumblr.com/avatar_e32e887541c2_128.png"
- Name: jphastings
  Title: Musings
  URL: http://blog.byjp.me/
  PortraitURL-16: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_16.png"
  PortraitURL-24: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_24.png"
  PortraitURL-30: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_30.png"
  PortraitURL-40: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_40.png"
  PortraitURL-48: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_48.png"
  PortraitURL-64: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_64.png"
  PortraitURL-96: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_96.png"
  PortraitURL-128: "http://30.media.tumblr.com/avatar_c92fbe5a1f68_128.png"
- Name: mwunsch
  Title: M. Wunsch
  URL: http://mwunsch.tumblr.com/
  PortraitURL-16: "http://26.media.tumblr.com/avatar_14a45e5585e1_16.png"
  PortraitURL-24: "http://26.media.tumblr.com/avatar_14a45e5585e1_24.png"
  PortraitURL-30: "http://26.media.tumblr.com/avatar_14a45e5585e1_30.png"
  PortraitURL-40: "http://26.media.tumblr.com/avatar_14a45e5585e1_40.png"
  PortraitURL-48: "http://26.media.tumblr.com/avatar_14a45e5585e1_48.png"
  PortraitURL-64: "http://26.media.tumblr.com/avatar_14a45e5585e1_64.png"
  PortraitURL-96: "http://26.media.tumblr.com/avatar_14a45e5585e1_96.png"
  PortraitURL-128: "http://26.media.tumblr.com/avatar_14a45e5585e1_128.png"
- Name: danielpietzsch
  Title: Daniel's Blog
  URL: http://blog.danielpietzsch.com/
  PortraitURL-16: "http://27.media.tumblr.com/avatar_248a5953e87b_16.png"
  PortraitURL-24: "http://27.media.tumblr.com/avatar_248a5953e87b_24.png"
  PortraitURL-30: "http://27.media.tumblr.com/avatar_248a5953e87b_30.png"
  PortraitURL-40: "http://27.media.tumblr.com/avatar_248a5953e87b_40.png"
  PortraitURL-48: "http://27.media.tumblr.com/avatar_248a5953e87b_48.png"
  PortraitURL-64: "http://27.media.tumblr.com/avatar_248a5953e87b_64.png"
  PortraitURL-96: "http://27.media.tumblr.com/avatar_248a5953e87b_96.png"
  PortraitURL-128: "http://27.media.tumblr.com/avatar_248a5953e87b_128.png"